---
title: "Reproducible research, project #1"
author: "Karl Kuder"
date: "June 30, 2016"
output: html_document
---

# File processing and summaries
Unzip and read the input data file. Build daily and interval summmaries.

```{r}
unzip("activity.zip")
Activity <- read.csv("activity.csv")
DailySum <- with(Activity, tapply(steps, date, sum))
IntMean <- aggregate(steps ~ interval, data = Activity, FUN = mean)
```





# Total number of steps taken each day
```{r}
hist(DailySum, xlab = "Steps", ylab = "Days", 
     main = "Number of days at each level of steps", breaks = 10)
meanSteps <- mean(DailySum, na.rm=TRUE)
medianSteps <- median(DailySum, na.rm=TRUE)
```

The mean number of steps taken each day is `r format(meanSteps, nsmall=2)`

The median number of steps taken each day is `r medianSteps`



# Daily pattern
```{r}
with(IntMean, plot(interval, steps, type = "l"))
maxInterval <- with(IntMean, interval[(steps == max(steps))])
```

The interval with the maximum average number of steps is `r maxInterval`